import os
import requests
from google.adk import Agent
from google.adk.tools.tool_context import ToolContext

# --- beehiiv API Publishing Tools ---

_POST_CREATED_IN_SESSION = False
_LAST_CREATED_POST_INFO = None

def create_beehiiv_post(
    tool_context: ToolContext,
    title: str,
    subtitle: str,
    status: str = "draft"
) -> dict:
    """Creates a newsletter post in beehiiv via API v2 using the pre-built output_newsletter.html from disk.
    
    Args:
        title: Title/Headline of the newsletter post.
        subtitle: Subtitle/preview text for the post.
        status: Post status - 'draft' for review or 'confirmed' for immediate email publish.
    """
    global _POST_CREATED_IN_SESSION, _LAST_CREATED_POST_INFO
    
    if _POST_CREATED_IN_SESSION and _LAST_CREATED_POST_INFO:
        return {
            "success": True,
            "notice": "Post already created in this run. Skipping duplicate creation.",
            "post_info": _LAST_CREATED_POST_INFO
        }
        
    api_key = os.getenv("BEEHIIV_API_KEY")
    pub_id = os.getenv("BEEHIIV_PUBLICATION_ID")
    
    if not api_key or api_key.startswith("your_"):
        return {
            "error": "BEEHIIV_API_KEY is missing or unconfigured in .env",
            "status": "simulation_mode"
        }
        
    if not pub_id or pub_id.startswith("pub_your_"):
        return {
            "error": "BEEHIIV_PUBLICATION_ID is missing or unconfigured in .env",
            "status": "simulation_mode"
        }
    
    # Read the pre-built HTML from disk (generated by publisher_designer_agent.py)
    html_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output_newsletter.html")
    try:
        with open(html_path, "r", encoding="utf-8") as f:
            body_content_html = f.read()
    except FileNotFoundError:
        return {"error": f"output_newsletter.html not found at {html_path}. Run the publisher agent first."}
        
    url = f"https://api.beehiiv.com/v2/publications/{pub_id}/posts"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    target_status = os.getenv("BEEHIIV_POST_STATUS", status)
    
    # --- Strip all emojis from title and subtitle for clean email subject lines ---
    import re
    emoji_regex = re.compile(r'[\U00010000-\U0010FFFF\u2600-\u27FF\u2300-\u23FF\u2B00-\u2BFF\u200D\uFE0F]')
    clean_title = emoji_regex.sub('', title).strip()
    clean_subtitle = emoji_regex.sub('', subtitle).strip()

    payload = {
        "title": clean_title,
        "subtitle": clean_subtitle,
        "status": target_status,
        "body_content": body_content_html
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        if response.status_code in [200, 201]:
            data = response.json()
            post_data = data.get("data", {})
            _POST_CREATED_IN_SESSION = True
            _LAST_CREATED_POST_INFO = {
                "post_id": post_data.get("id"),
                "status": post_data.get("status"),
                "web_url": post_data.get("web_url")
            }
            return {
                "success": True,
                "post_id": post_data.get("id"),
                "status": post_data.get("status"),
                "web_url": post_data.get("web_url"),
                "message": f"Successfully created beehiiv post '{title}' as {status}"
            }
        else:
            return {
                "error": f"beehiiv API request failed with status {response.status_code}",
                "details": response.text
            }
    except Exception as e:
        return {"error": f"Exception connecting to beehiiv API: {str(e)}"}

# --- beehiiv Publisher Agent Definition ---

BEEHIIV_PUBLISHER_INSTRUCTION = """You are an automated beehiiv Newsletter Publisher Agent for 'Cars Never Die'.

CRITICAL RULE: Call the `create_beehiiv_post` tool EXACTLY ONCE. Do NOT retry or call it multiple times.

NO EMOJIS: Do NOT include any emojis in the title or subtitle under any circumstances. Keep titles and subject lines 100% clean and emoji-free.

Your procedure:
1. Generate a compelling, clean title and subtitle based on the newsletter content (NO emojis allowed).
2. Make a SINGLE call to `create_beehiiv_post` with status='draft'. The HTML body is automatically read from output_newsletter.html on disk — you do NOT need to pass it.
3. Stop and return the resulting post ID and web_url."""

beehiiv_publisher_agent = Agent(
    name="beehiiv_publisher",
    model="gemini-3.5-flash",
    instruction=BEEHIIV_PUBLISHER_INSTRUCTION,
    tools=[create_beehiiv_post]
)
